CREATE SCHEMA IF NOT EXISTS `usuarios_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `usuarios_db` ;

DROP TABLE IF EXISTS Usuarios;

CREATE TABLE Usuarios (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    senha VARCHAR(255),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
